### ISSUE TITLE
from <window> siddhiAppCreationException 

### ISSUE THREAD

**Issue by xiesen310** [wso2/siddhi-sdk#12]
**Description:**
Hello, when I was using siddhi,I found that something about the error of siddhiAppCreationException would be reported as I used the statement of from <window> in partition.What's more,no detailed message about this error was described. 

```
@App:name("firstrule")
@App:description("Description of the plan") 

@source(type='http',receiver.url = 'http://localhost:8080/exchange',headers = "'content-type:application/json'",@map(type='json'))
define stream exchangeStream(id int, price double, exchangeWay int, exChangeNum long);
@sink(type='log',@map(type='json'))
define stream outputStream(times string, id int, invalidCount long,price double);
define window dataCacheWindow (times string, id int, invalidCount long,price double) timeBatch(10 second);

partition with (id of exchangeStream)
begin

from exchangeStream select time:currentTime() as times, id, count(id) as invalidCount, price group by id having invalidCount > 1 insert into dataCacheWindow;
from dataCacheWindow select times, id, invalidCount, price insert into outputStream;

end
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by RAVEENSR** [comment]
This issue is related to siddhi and it is tracked in https://github.com/wso2/siddhi/issues/797 . Hence we can close this.
